services:
  - type: web
    name: edunova-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: CHANNEL_USERNAME
        sync: false
      - key: CHANNEL_URL
        sync: false