services:
  - type: web
    name: edunova-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        value: "7180980386,1219356053"
      - key: CHANNEL_USERNAME
        value: "@edunova_maktabi"
      - key: CHANNEL_URL
        value: "https://t.me/edunova_maktabi"
